### ISSUE TITLE
How to make it work on OpenSUSE Leap

### ISSUE THREAD

**Issue by boogiefromzk** [ivyl/obs-lv2#2]
On OpenSUSE Leap 15.1 to compile I had to:

Inspired by https://discourse.zynthian.org/t/cannot-start-dexed-jalv/2994/3 doing those links
```
ln -s /usr/lib64/lv2/options.lv2 /usr/local/include/lv2/options
ln -s /usr/lib64/lv2/ui.lv2 /usr/local/include/lv2/ui
ln -s /usr/lib64/lv2/lv2core.lv2 /usr/local/include/lv2/core
ln -s /usr/lib64/lv2/urid.lv2 /usr/local/include/lv2/urid
ln -s /usr/lib64/lv2/atom.lv2 /usr/local/include/lv2/atom
ln -s /usr/lib64/lv2/state.lv2 /usr/local/include/lv2/state
ln -s /usr/lib64/lv2/instance-access.lv2 /usr/local/include/lv2/instance-access
ln -s /usr/lib64/lv2/data-access.lv2 /usr/local/include/lv2/data-access
```

On gcc 7.5 compilation fails, so used 9
`sudo zypper in gcc9-c++`

Inspired by https://stackoverflow.com/questions/7832892/how-to-change-the-default-gcc-compiler-in-ubuntu
```
sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-9 9
sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-7 7
```
you can switch later using: `sudo update-alternatives --config g++`

compiling as in readme:
```
meson build
ninja -C build
```

system-wide installation does nothing, so copying library manually:
`sudo cp ./build/obs-lv2.so /usr/lib/obs-plugins/`

**Comment by ivyl** [comment]
Seems like the distribution you are using comes with dated packages.

LV2 1.16.0 released on 2019-02-02 comes with the simplified include paths we are using here. I'll start requiring version >= 1.16 in meson.build.

As of GCC 7 - all the distros I personally use come with either GCC 9 or 10 for a long time now. If support for GCC 7 is important and it doesn't take much to make it compile pull request is welcome.

Installation definitely needs overhauling. I need to see how other plugins are determining the installation path. Thanks for confirming that  `/usr/lib/obs-plugins/obs-lv2.so` works for you on your distro.

**Comment by boogiefromzk** [comment]
It's stable current OpenSUSE Leap 15.1, it has those versions.

**Comment by ivyl** [comment]
The plugin now builds with GCC 7 and `--prefix=/usr` switch is already included in the README.
