### ISSUE TITLE
"Nothing to install"

### ISSUE THREAD

**Issue by ghost** [ivyl/obs-lv2#4]
Everything builds fine, but when I go to do a system wide install, it just tells me there is nothing to install.

**Comment by ivyl** [comment]
If this still doesn't work for you feel free to reopen and let me know what distribution and what OBS (distro provided one, some portable installation) you are using.

This will allow me to debug the problem in the container.

**Comment by ghost** [comment]
> If this still doesn't work for you feel free to reopen and let me know what distribution and what OBS (distro provided one, some portable installation) you are using.
> 
> This will allow me to debug the problem in the container.

Yes, works as intended now, thanks!
