### ISSUE TITLE
Only Calf and Guitarix Plugin visible

### ISSUE THREAD

**Issue by nicolalandro** [ivyl/obs-lv2#6]
I have installed also tap, lsp and other lv2 plugin to my machine. I see it with Carla and also with Ardour, but not with This plugin. I do something wrong?

OS: Linux Mint 20.1
OBS: 26.1.1

**Comment by paperbenni** [comment]
I am having the same issue, OBS 26.1.0-2
Calf is showing up, noise-repellent from the arch repos is not

**Comment by ivyl** [comment]
This should be solved. We no longer do filtering using plugin types, which apparently is broken. See #9 for details.
